-- 1. COPY THIS ENTIRE CONTENT
-- 2. GO TO SUPABASE DASHBOARD -> SQL EDITOR
-- 3. PASTE AND RUN

-- CREATE TABLES IF THEY ARE MISSING

-- 1. CART ITEMS
create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  product_id bigint references public.products(id),
  quantity integer default 1,
  size text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. ORDERS
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text unique,
  user_id uuid references public.profiles(id),
  total_amount numeric,
  status text default 'pending',
  shipping_address jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. ORDER ITEMS
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  product_id bigint references public.products(id),
  quantity integer,
  price numeric,
  size text
);

-- 4. TRANSACTIONS
create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  order_id bigint references public.orders(id),
  amount numeric,
  status text,
  payment_id text,
  transaction_id text,
  payment_method text,
  payment_status text,
  razorpay_order_id text,
  razorpay_payment_id text,
  razorpay_signature text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);


-- ENABLE SECURITY (RLS)
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.transactions enable row level security;


-- POLICIES (Use DO block to avoid errors if they exist, or just DROP and RECREATE)
-- We will use 'create policy if not exists' pattern via a helper function or just ignore errors?
-- Postgres doesn't have 'CREATE POLICY IF NOT EXISTS' easily without a function. 
-- Simple way: Drop then Create.

drop policy if exists "Users can view own cart." on cart_items;
create policy "Users can view own cart." on cart_items for select using ( auth.uid() = user_id );

drop policy if exists "Users can insert into own cart." on cart_items;
create policy "Users can insert into own cart." on cart_items for insert with check ( auth.uid() = user_id );

drop policy if exists "Users can update own cart." on cart_items;
create policy "Users can update own cart." on cart_items for update using ( auth.uid() = user_id );

drop policy if exists "Users can delete from own cart." on cart_items;
create policy "Users can delete from own cart." on cart_items for delete using ( auth.uid() = user_id );

-- ORDERS POLICIES
drop policy if exists "Users can view own orders." on orders;
create policy "Users can view own orders." on orders for select using ( auth.uid() = user_id );

drop policy if exists "Users can insert orders." on orders;
create policy "Users can insert orders." on orders for insert with check ( auth.uid() = user_id );

drop policy if exists "Admins can view all orders." on orders;
create policy "Admins can view all orders." on orders for select using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- ORDER ITEMS POLICIES
drop policy if exists "Viewable by order owner" on order_items;
create policy "Viewable by order owner" on order_items for select using ( exists ( select 1 from orders where id = order_items.order_id and user_id = auth.uid() ) );

drop policy if exists "Users can insert order items" on order_items;
create policy "Users can insert order items" on order_items for insert with check ( 
  exists ( select 1 from orders where id = order_items.order_id and user_id = auth.uid() )
);

-- TRANSACTIONS POLICIES
drop policy if exists "Users view own transactions" on transactions;
create policy "Users view own transactions" on transactions for select using ( auth.uid() = user_id );

drop policy if exists "Users can insert transactions" on transactions;
create policy "Users can insert transactions" on transactions for insert with check ( auth.uid() = user_id );

drop policy if exists "Users can update transactions" on transactions;
create policy "Users can update transactions" on transactions for update using ( auth.uid() = user_id );


-- REFRESH SCHEMA CACHE
NOTIFY pgrst, 'reload config';
