
-- 7. CART ITEMS
create table public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null, -- Reference auth.users directly to avoid Profile dependency issues
  product_id bigint references public.products(id),
  quantity integer default 1,
  size text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.cart_items enable row level security;

create policy "Users can view own cart."
  on cart_items for select
  using ( auth.uid() = user_id );

create policy "Users can insert into own cart."
  on cart_items for insert
  with check ( auth.uid() = user_id );

create policy "Users can update own cart."
  on cart_items for update
  using ( auth.uid() = user_id );

create policy "Users can delete from own cart."
  on cart_items for delete
  using ( auth.uid() = user_id );
